const state = {
  mode: 'customer', customerStep: 'home', selectedType: '기술 문제', activeConversation: 'c1', composerMode: 'reply', modal: null, requestNumber: 1049,
  conversations: [
    {id:'c1', name:'Maya Chen', org:'Acme Corp', title:'API requests returning 502 in EU-West', preview:'최근 배포 이후 502 응답이 발생하고 있습니다.', status:'진행 중', priority:'높음', time:'4분', assignee:'Alex Kim', tags:['API','EU-West'], created:'오늘 09:42', caseId:'CASE-1048', incident:'INC-203', issue:'PROD-1842', messages:[{from:'Maya Chen',type:'customer',time:'09:42',text:'최근 배포 이후 EU-West Public API 요청에서 502 응답이 발생하고 있습니다.\n\nRequest ID: req_89a21\n환경: Production · API v3\n영향: EU 고객의 결제가 차단되었습니다.'},{from:'Alex Kim',type:'agent',time:'09:48',text:'제보 감사합니다. 플랫폼 팀과 함께 조사 중이며 이 대화에서 곧 업데이트하겠습니다.'},{from:'Alex Kim',type:'internal',time:'09:49',text:'@Platform Team 09:40 UTC 전후 EU-West 오류를 확인 부탁드립니다. Request ID와 고객 로그를 첨부했습니다.'}]},
    {id:'c2', name:'Noah Patel', org:'Nimbus Labs', title:'SCIM sync has stopped', preview:'토큰 교체 이후 프로비저닝이 중단되었습니다.', status:'팀 답변 대기', priority:'높음', time:'18분', assignee:'Jamie Park', tags:['SCIM']},
    {id:'c3', name:'Sofia Rossi', org:'Velo', title:'Invoice address update', preview:'청구지 주소 변경을 요청했습니다.', status:'고객 답변 대기', priority:'보통', time:'1시간', assignee:'Alex Kim', tags:['Billing']},
    {id:'c4', name:'Liam Wilson', org:'Orbit Systems', title:'Webhook retry policy', preview:'최대 재시도 기간을 문의했습니다.', status:'신규', priority:'보통', time:'2시간', assignee:'미배정', tags:['제품 문의']}
  ]
};
const $ = (s) => document.querySelector(s);
function conv(){ return state.conversations.find(c=>c.id===state.activeConversation); }
function badge(priority){ return `<span class="badge ${priority==='높음'?'red':'blue'}">${priority==='높음'?'● 높음':'보통'}</span>`; }
function statusBadge(status){ return `<span class="badge ${status.includes('대기')?'amber':'blue'}">${status}</span>`; }
function render(){ $('#app').innerHTML = `<div class="app-shell"><header class="topbar"><div class="brand"><span class="brand-mark">R</span>RelayDesk</div><div class="mode-switch"><button class="${state.mode==='customer'?'active':''}" onclick="setMode('customer')">고객 화면</button><button class="${state.mode==='agent'?'active':''}" onclick="setMode('agent')">지원 워크스페이스</button></div><div class="avatar">AK</div></header>${state.mode==='customer'?customerView():agentView()}</div>${state.modal?modal():''}`; }
function customerView(){ if(state.customerStep==='types') return typeView(); if(state.customerStep==='form') return formView(); if(state.customerStep==='chat') return chatView(); return `<main class="customer-wrap"><div class="customer-header"><div><div class="eyebrow">RELAYDESK SUPPORT</div><h1>How can we help?</h1><p class="muted">워크스페이스, 제품 또는 계정에 관해 도움을 드립니다.</p></div></div><div class="card status-card"><span class="status-dot"></span><div><strong>모든 시스템이 정상 운영 중입니다</strong><span class="muted">현재 진행 중인 장애가 없습니다.</span></div></div><div class="section-title"><span>추천 도움말</span><a class="link-button">도움말 센터</a></div><div class="card"><div class="article"><div><strong>API 서비스 상태 확인</strong><br><span>현재 장애 및 점검 일정</span></div><span>›</span></div><div class="article"><div><strong>API 오류 해결 방법</strong><br><span>일반적인 4xx·5xx 응답 코드</span></div><span>›</span></div></div><div class="customer-cta"><button class="primary" onclick="customerStep('types')">지원팀에 문의하기</button></div><div class="section-title"><span>최근 대화</span></div><div class="card"><strong>API 요청 시간 초과</strong><br><span class="muted">해결됨 · 6월 12일</span></div></main>`; }
function typeView(){const types=[['기술 문제','오류, API 실패 또는 예상치 못한 동작을 신고합니다'],['계정 및 접근','로그인, 역할, 워크스페이스 접근을 문의합니다'],['결제','청구서, 결제, 구독 관련 문의입니다'],['보안 및 컴플라이언스','보안 검토 및 컴플라이언스 요청입니다'],['제품 문의','제품 또는 기능 사용 방법을 문의합니다'],['기능 제안','개선 아이디어를 제안합니다']]; return `<main class="customer-wrap"><button class="back" onclick="customerStep('home')">← 이전</button><div class="eyebrow">NEW REQUEST</div><h1>What do you need help with?</h1><p class="muted">문의 내용과 가장 가까운 항목을 선택하세요.</p>${types.map(([n,d])=>`<button class="type-option ${n===state.selectedType?'selected':''}" onclick="selectType('${n}')"><strong>${n}</strong><span>${d}</span></button>`).join('')}<div class="customer-cta"><button class="primary" onclick="customerStep('form')">계속</button></div></main>`;}
function formView(){return `<main class="customer-wrap"><button class="back" onclick="customerStep('types')">← 이전</button><div class="eyebrow">TECHNICAL ISSUE</div><h1>Tell us what happened</h1><p class="muted">조사를 빠르게 진행할 수 있도록 워크스페이스 정보를 미리 입력했습니다.</p><form onsubmit="submitRequest(event)"><div class="grid-2"><div class="field"><label>제품</label><select><option>Public API</option></select></div><div class="field"><label>환경</label><select><option>Production</option></select></div></div><div class="grid-2"><div class="field"><label>리전</label><select><option>EU-West</option></select></div><div class="field"><label>버전</label><input value="API v3" /></div></div><div class="field"><label>오류 코드</label><input value="502" /></div><div class="field"><label>어떤 문제가 발생했나요?</label><textarea required>최근 배포 이후 API 요청에서 502 응답이 발생합니다. EU 고객의 결제가 차단되었습니다.</textarea></div><div class="field"><label>Request ID (선택)</label><input value="req_89a21" /></div><button class="primary" type="submit">문의 보내기</button></form></main>`;}
function chatView(){let c=conv(); return `<main class="customer-wrap"><button class="back" onclick="customerStep('home')">← 모든 대화</button><div class="eyebrow">${c.caseId||'NEW REQUEST'}</div><h1>${c.title}</h1><div class="message-status"><strong>${c.status}</strong> · 기술 지원팀이 조사 중입니다.</div>${c.incident?`<div class="incident-banner"><strong>Incident 연결됨 · EU-West API latency</strong><span>EU-West의 API 오류 증가를 조사하고 있습니다. 다음 업데이트는 30분 내 제공됩니다.</span></div>`:''}<div class="chat">${(c.messages||[]).filter(m=>m.type!=='internal').map(m=>`<div class="bubble ${m.type==='customer'?'customer':'agent'}">${m.text.replace(/\n/g,'<br>')}</div><div class="message-meta ${m.type==='agent'?'right':''}">${m.from} · ${m.time}</div>`).join('')}</div><div class="composer"><input placeholder="답장을 입력하세요" /><button onclick="showToast('지원팀에 답장을 보냈습니다')">전송</button></div></main>`;}
function agentView(){let c=conv(); return `<main class="agent-shell"><nav class="nav">${['인박스','케이스','고객','조직','Incident','지식','분석'].map((n,i)=>`<button class="nav-item ${i===0?'active':''}">${n}</button>`).join('')}</nav><aside class="sidebar"><div class="sidebar-head"><h2>Inbox</h2><div class="queue-tabs"><button class="active">진행 중 전체</button><button>내 담당</button><button>SLA 위험</button></div></div>${state.conversations.map(x=>`<button class="conversation ${x.id===c.id?'active':''}" onclick="openConversation('${x.id}')"><div class="row"><strong>${x.name}</strong>${badge(x.priority)}</div><small>${x.org} · ${x.time}</small><p>${x.title}</p><div class="row">${statusBadge(x.status)}<small>${x.assignee==='미배정'?'미배정':x.assignee}</small></div></button>`).join('')}</aside><section class="detail"><div class="detail-head"><div class="row"><div><h2>${c.title}</h2><div class="meta"><span>${c.caseId||'케이스 없음'}</span> · ${statusBadge(c.status)} · ${badge(c.priority)}</div></div><button class="secondary" onclick="changeStatus()">상태 변경</button></div><div class="tabs"><button class="active">대화</button><button>케이스 상세</button><button>활동</button></div></div><div class="thread">${thread(c)}</div><div class="composer-agent"><div class="composer-type"><button class="${state.composerMode==='reply'?'active':''}" onclick="setComposer('reply')">답장</button><button class="${state.composerMode==='internal'?'active':''}" onclick="setComposer('internal')">내부 메모</button></div><textarea id="agent-composer" placeholder="${state.composerMode==='internal'?'내부 메모를 작성하세요…':c.name+'님에게 답장하기…'}"></textarea><div class="composer-actions"><button class="link-button" onclick="useMacro()">매크로 사용</button><button class="send" onclick="sendMessage()">${state.composerMode==='internal'?'메모 추가':'답장 보내기'}</button></div></div></section><aside class="context">${context(c)}</aside></main>`;}
function thread(c){let messages=c.messages||[]; return `<div class="thread-event">대화 생성 · ${c.created||'오늘'}</div>${messages.map(m=>`<div class="thread-message ${m.type==='internal'?'internal':''}"><div class="avatar">${m.from.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div class="content"><strong>${m.from}</strong> ${m.type==='internal'?'<span class="internal-label"> · 내부 메모</span>':''}<p>${m.text}</p><span class="muted" style="font-size:11px">${m.time}</span></div></div>`).join('')}${c.incident?'<div class="thread-event">Incident INC-203 연결됨 · EU-West API latency</div>':''}`;}
function context(c){return `<div class="context-head"><h3>고객 컨텍스트</h3><button class="link-button">프로필 보기</button></div><div class="context-section"><h4>${c.name} <span class="muted" style="font-weight:400">· ${c.org}</span></h4><dl class="key-value"><dt>플랜</dt><dd>Enterprise</dd><dt>워크스페이스</dt><dd>Acme Production</dd><dt>시간대</dt><dd>UTC+1 · 10:02 AM</dd><dt>언어</dt><dd>영어</dd></dl></div><div class="context-section"><h4>기술 컨텍스트</h4><dl class="key-value"><dt>제품</dt><dd>Public API</dd><dt>환경</dt><dd>Production</dd><dt>리전</dt><dd>EU-West</dd><dt>버전</dt><dd>API v3</dd><dt>오류 코드</dt><dd>502</dd><dt>Request ID</dt><dd>req_89a21</dd></dl></div><div class="context-section"><h4>작업</h4><div class="action-grid"><button onclick="openModal('case')">지원 케이스 생성</button><button onclick="openModal('incident')">${c.incident?'Incident 연결 변경':'Incident 연결'}</button><button onclick="openModal('issue')">${c.issue?'개발 이슈 보기':'개발 이슈 생성'}</button><button onclick="assignSelf()">나에게 배정</button></div></div><div class="context-section"><h4>연결된 작업</h4>${c.incident?`<div class="linked"><strong>INC-203 · EU-West API latency</strong><span class="muted">조사 중 · Platform Team</span></div>`:'<p class="muted">연결된 Incident가 없습니다</p>'}${c.issue?`<div class="linked"><strong>${c.issue} · API requests fail in EU-West</strong><span class="muted">진행 중 · Platform Team</span></div>`:''}</div><div class="context-section"><h4>최근 활동</h4><ul class="timeline"><li>API v3 배포 · 09:28</li><li>유사 이슈 해결 · 6월 12일</li><li>Enterprise 갱신 · 6월 3일</li></ul></div>`;}
function modal(){const cfg={case:['지원 케이스 생성','이 기술 대화를 구조화된 지원 케이스로 전환합니다.','CASE-1048'],incident:['Incident 연결','이 대화를 진행 중인 EU-West API latency Incident에 연결합니다.','INC-203'],issue:['개발 이슈 생성','선택한 메시지와 기술 컨텍스트를 포함한 시뮬레이션 이슈를 생성합니다.','PROD-1842']}[state.modal];return `<div class="modal-backdrop"><div class="modal"><h2>${cfg[0]}</h2><p class="muted">${cfg[1]}</p><div class="field"><label>${state.modal==='issue'?'개발 담당 팀':'참조 번호'}</label>${state.modal==='issue'?'<select><option>Platform Team</option></select>':`<input value="${cfg[2]}" readonly />`}</div>${state.modal==='issue'?'<div class="field"><label>우선순위</label><select><option>높음</option></select></div>':''}<div class="actions"><button class="secondary" onclick="closeModal()">취소</button><button class="send" onclick="confirmModal()">확인</button></div></div></div>`;}
function setMode(m){state.mode=m; render();} function customerStep(s){state.customerStep=s; render();} function selectType(t){state.selectedType=t; render();}
function submitRequest(e){e.preventDefault(); let c={id:'c'+Date.now(),name:'Maya Chen',org:'Acme Corp',title:'API requests returning 502 in EU-West',preview:'최근 배포 이후 API 요청에서 502 응답이 발생합니다.',status:'신규',priority:'높음',time:'방금',assignee:'미배정',tags:['API','EU-West'],created:'방금 전',messages:[{from:'Maya Chen',type:'customer',time:'방금',text:'최근 배포 이후 API 요청에서 502 응답이 발생합니다. EU 고객의 결제가 차단되었습니다.\n\nRequest ID: req_89a21\n환경: Production · API v3 · EU-West'}]}; state.conversations.unshift(c); state.activeConversation=c.id; state.requestNumber+=1; state.customerStep='chat'; render(); showToast('기술 지원팀에 문의를 보냈습니다');}
function openConversation(id){state.activeConversation=id; render();} function setComposer(m){state.composerMode=m; render();}
function sendMessage(){let input=$('#agent-composer'), text=input.value.trim(); if(!text) return showToast('메시지를 먼저 작성하세요'); let c=conv(); c.messages=c.messages||[]; c.messages.push({from:'Alex Kim',type:state.composerMode==='internal'?'internal':'agent',time:'방금',text}); if(state.composerMode==='reply') c.status='고객 답변 대기'; render(); showToast(state.composerMode==='internal'?'내부 메모를 추가했습니다':'답장을 보냈습니다');}
function useMacro(){let input=$('#agent-composer'); input.value='제보 감사합니다. 현재 담당 팀에서 문제를 조사하고 있으며, 새로운 정보가 확인되는 대로 안내해 드리겠습니다.'; input.focus();}
function openModal(m){state.modal=m; render();} function closeModal(){state.modal=null;render();} function confirmModal(){let c=conv(); if(state.modal==='case')c.caseId='CASE-1048'; if(state.modal==='incident')c.incident='INC-203'; if(state.modal==='issue')c.issue='PROD-1842'; let label=state.modal==='case'?'지원 케이스를 생성했습니다':state.modal==='incident'?'Incident를 연결했습니다':'개발 이슈를 생성했습니다'; state.modal=null; render(); showToast(label);}
function changeStatus(){let c=conv(); c.status=c.status==='진행 중'?'고객 답변 대기':'진행 중'; render(); showToast('상태를 '+c.status+'(으)로 변경했습니다');} function assignSelf(){conv().assignee='Alex Kim';render();showToast('나에게 배정했습니다');} function showToast(t){let el=document.createElement('div');el.className='toast';el.textContent=t;document.body.append(el);setTimeout(()=>el.remove(),2400);} render();
