import { data, NOW } from './data.js';
import { state, setState } from './state.js';

const app = document.querySelector('#app');
const menus = [['inbox', '인박스'], ['cases', '케이스'], ['customers', '고객'], ['organizations', '조직'], ['incidents', 'Incident'], ['knowledge', '지식'], ['analytics', '분석']];
const find = (items, id) => items.find((item) => item.id === id);
const esc = (value = '') => String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[c]);
const status = (v) => ({ New: '신규', Open: '진행 중', Resolved: '해결됨', Closed: '종료됨', 'Waiting for customer': '고객 답변 대기', 'Waiting for team': '팀 답변 대기', Investigating: '조사 중', Identified: '원인 확인', Monitoring: '모니터링' }[v] || v);
const badge = (text, tone = 'blue') => `<span class="badge ${tone}">${esc(text)}</span>`;
const list = (items, empty = '연결된 항목이 없습니다.') => items.length ? items.join('') : `<p class="muted">${empty}</p>`;
const openCase = (item) => !['Resolved', 'Closed'].includes(item.status);
const relatedCases = (type, id) => data.cases.filter((c) => c[`${type}Id`] === id);
const latestUpdate = (incident) => incident?.updates?.slice().sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0];
const incidentCounts = (id) => { const cs = data.cases.filter((c) => c.incidentId === id); return { cases: cs, conversations: data.conversations.filter((c) => c.incidentId === id), customers: new Set(cs.map((c) => c.customerId)).size, organizations: new Set(cs.map((c) => c.organizationId)).size }; };
const sla = (item) => { if (['Resolved', 'Closed'].includes(item.status)) return ['완료', 'blue']; const mins = Math.round((new Date(item.slaDueAt) - NOW) / 60000); if (mins < 0) return [`${Math.abs(mins)}분 초과`, 'red']; if (mins <= 60) return [`${mins}분 남음`, 'amber']; return [`${Math.ceil(mins / 60)}시간 남음`, 'blue']; };
const filter = (menu, key) => (state.filtersByMenu[menu] || {})[key] || '';
function setFilter(menu, key, value) { setState({ filtersByMenu: { ...state.filtersByMenu, [menu]: { ...(state.filtersByMenu[menu] || {}), [key]: value } } }); }
function nav() { return `<nav class="nav">${menus.map(([id, label]) => `<button class="nav-item ${state.activeAgentMenu === id ? 'active' : ''}" data-action="menu" data-id="${id}">${label}</button>`).join('')}</nav>`; }
function shell(content) { return `<div class="app-shell"><header class="topbar"><div class="brand"><span class="brand-mark">R</span>RelayDesk</div><div class="mode-switch"><button class="${state.mode === 'customer' ? 'active' : ''}" data-action="mode" data-id="customer">고객 화면</button><button class="${state.mode === 'agent' ? 'active' : ''}" data-action="mode" data-id="agent">지원 워크스페이스</button></div><div class="avatar">AK</div></header>${content}${state.toast ? `<div class="toast">${esc(state.toast)}</div>` : ''}</div>`; }
function entityShell(title, count, rows, detail, filters = '') { return `<main class="agent-shell case-shell">${nav()}<aside class="entity-list"><div class="entity-list-head"><div class="row"><h2>${title}</h2><span class="muted">${count}건</span></div>${filters}</div>${rows}</aside><section class="entity-detail">${detail}</section></main>`; }
function customerView() {
  const active = data.incidents.filter((i) => i.status !== 'Resolved');
  if (state.customerStep === 'form') { const f = state.customerForm; const field = (k, label, area = false) => `<div class="field"><label>${label}</label>${area ? `<textarea data-customer-field="${k}">${esc(f[k])}</textarea>` : `<input data-customer-field="${k}" value="${esc(f[k])}">`}</div>`; return `<main class="customer-wrap"><button class="back" data-action="customer-step" data-id="home">← 이전</button><div class="eyebrow">TECHNICAL ISSUE</div><h1>Tell us what happened</h1><div class="grid-2">${field('product', '제품')}${field('environment', '환경')}</div><div class="grid-2">${field('region', '리전')}${field('version', '버전')}</div><div class="grid-2">${field('errorCode', '오류 코드')}${field('requestId', 'Request ID')}</div>${field('impact', '고객 영향')}${field('reproductionSteps', '재현 절차', true)}${field('message', '어떤 문제가 발생했나요?', true)}<button class="primary" data-action="submit-request">문의 보내기</button></main>`; }
  if (state.customerStep === 'chat') { const c = find(data.conversations, state.selectedConversationId); const incident = find(data.incidents, c.incidentId); const up = latestUpdate(incident); return `<main class="customer-wrap"><button class="back" data-action="customer-step" data-id="home">← 모든 대화</button><div class="eyebrow">${c.caseId ? c.caseId.toUpperCase() : 'NEW REQUEST'}</div><h1>${esc(c.title)}</h1><div class="message-status"><strong>${status(c.status)}</strong> · 기술 지원팀이 확인 중입니다.</div>${incident ? `<div class="incident-banner"><strong>${esc(incident.title)} · ${status(incident.status)}</strong><span>${esc(up?.message || '최신 업데이트를 준비 중입니다.')}</span></div>` : ''}<div class="chat">${c.messages.filter((m) => m.type !== 'internal').map((m) => `<div class="bubble ${m.type === 'agent' ? 'agent' : 'customer'}">${esc(m.text)}</div><div class="message-meta ${m.type === 'agent' ? 'right' : ''}">${esc(m.from)} · ${m.time}</div>`).join('')}</div></main>`; }
  return `<main class="customer-wrap"><div class="eyebrow">RELAYDESK SUPPORT</div><h1>How can we help?</h1><div class="card status-card"><span class="status-dot ${active.length ? 'warning' : ''}"></span><div><strong>${active.length ? `${active.length}건의 서비스 이슈를 조사 중입니다` : '모든 시스템이 정상 운영 중입니다'}</strong><span class="muted">${active.length ? esc(active.map((i) => i.title).join(', ')) : '현재 진행 중인 장애가 없습니다.'}</span></div></div><div class="customer-cta"><button class="primary" data-action="customer-step" data-id="form">지원팀에 문의하기</button></div></main>`;
}
function inboxView() {
  const queue = state.inboxQueue === 'mine' ? data.conversations.filter((c) => c.assigneeId === 'm-alex') : data.conversations;
  const selected = queue.find((c) => c.id === state.selectedConversationId) || queue[0];
  if (!selected) return entityShell('Inbox', 0, `<div class="empty-state"><strong>대화가 없습니다</strong></div>`, '');
  const customer = find(data.customers, selected.customerId), org = find(data.organizations, selected.organizationId), incident = find(data.incidents, selected.incidentId), up = latestUpdate(incident), t = selected.technical;
  const rows = queue.map((c) => { const u = find(data.customers, c.customerId); return `<button class="conversation ${c.id === selected.id ? 'active' : ''}" data-action="conversation" data-id="${c.id}"><div class="row"><strong>${esc(u.name)}</strong>${badge(c.priority === 'High' ? '높음' : '보통', c.priority === 'High' ? 'red' : 'blue')}</div><small>${esc(find(data.organizations, c.organizationId).name)}</small><p>${esc(c.title)}</p><div class="row">${badge(status(c.status))}<small>${c.caseId ? c.caseId.toUpperCase() : '케이스 없음'}</small></div></button>`; }).join('');
  const messages = selected.messages.map((m) => `<div class="thread-message ${m.type === 'internal' ? 'internal' : ''}"><div class="avatar">${esc(m.from.split(' ').map((x) => x[0]).join('').slice(0, 2))}</div><div class="content"><strong>${esc(m.from)}</strong>${m.type === 'internal' ? '<span class="internal-label"> · 내부 메모</span>' : ''}<p>${esc(m.text)}</p><span class="muted">${m.time}</span></div></div>`).join('');
  const composer = `<div class="composer-agent"><div class="composer-type"><button class="${state.composerMode === 'reply' ? 'active' : ''}" data-action="composer-mode" data-id="reply">답장</button><button class="${state.composerMode === 'internal' ? 'active' : ''}" data-action="composer-mode" data-id="internal">내부 메모</button></div><textarea data-composer-input placeholder="${state.composerMode === 'internal' ? '내부 메모를 작성하세요…' : '고객에게 답장하기…'}">${esc(state.composerText)}</textarea><div class="composer-actions"><button class="link-button" data-action="use-macro">매크로 사용</button><button class="link-button" data-action="open-knowledge">문서 삽입</button><button class="send" data-action="send-message">${state.composerMode === 'internal' ? '메모 추가' : '답장 보내기'}</button></div></div>`;
  return `<main class="agent-shell">${nav()}<aside class="sidebar"><div class="sidebar-head"><div class="row"><h2>Inbox</h2><span class="muted">${queue.length}건</span></div><div class="queue-tabs"><button class="${state.inboxQueue === 'all' ? 'active' : ''}" data-action="inbox-queue" data-id="all">진행 중 전체</button><button class="${state.inboxQueue === 'mine' ? 'active' : ''}" data-action="inbox-queue" data-id="mine">내 담당</button></div></div>${rows}</aside><section class="detail"><div class="detail-head"><h2>${esc(selected.title)}</h2><div class="meta">${selected.caseId ? `<button class="link-button" data-action="open-case" data-id="${selected.caseId}">${selected.caseId.toUpperCase()} 보기</button>` : `<button class="link-button" data-action="create-case" data-id="${selected.id}">지원 케이스 생성</button>`} · ${status(selected.status)}</div></div>${incident ? `<div class="incident-inline"><strong>${esc(incident.title)} · ${status(incident.status)}</strong><span>${esc(up?.message || '')}</span></div>` : ''}<div class="thread">${messages}</div>${composer}</section><aside class="context"><div class="context-head"><h3>고객 컨텍스트</h3></div><div class="context-section"><h4>${esc(customer.name)}</h4><dl class="key-value"><dt>조직</dt><dd><button class="link-button" data-action="open-organization" data-id="${org.id}">${esc(org.name)}</button></dd><dt>플랜</dt><dd>${esc(org.plan)}</dd><dt>시간대</dt><dd>${customer.timezone}</dd></dl></div><div class="context-section"><h4>기술 컨텍스트</h4><dl class="key-value"><dt>제품</dt><dd>${esc(t.product)}</dd><dt>환경</dt><dd>${esc(t.environment)}</dd><dt>리전</dt><dd>${esc(t.region)}</dd><dt>버전</dt><dd>${esc(t.version)}</dd><dt>오류 코드</dt><dd>${esc(t.errorCode || '—')}</dd><dt>Request ID</dt><dd>${esc(t.requestId || '—')}</dd><dt>영향</dt><dd>${esc(t.impact)}</dd></dl></div><div class="context-section">${selected.caseId ? `<button class="linked" data-action="open-case" data-id="${selected.caseId}"><strong>${selected.caseId.toUpperCase()}</strong><span>케이스 상세 보기</span></button>` : `<button class="secondary" data-action="create-case" data-id="${selected.id}">지원 케이스 생성</button>`}</div></aside></main>`;
}
function casesView() { const q = filter('cases', 'query').toLowerCase(), st = filter('cases', 'status'), sev = filter('cases', 'severity'), inc = filter('cases', 'incident'); const items = data.cases.filter((c) => `${c.id} ${c.title} ${find(data.organizations, c.organizationId).name} ${c.product}`.toLowerCase().includes(q) && (!st || c.status === st) && (!sev || c.severity === sev) && (!inc || (inc === 'linked' ? c.incidentId : !c.incidentId))).sort((a,b) => a.severity.localeCompare(b.severity) || new Date(a.slaDueAt) - new Date(b.slaDueAt)); const selected = items.find((c) => c.id === state.selectedCaseId) || items[0]; const filters = searchFilters('cases', 'Case ID, 제목, 조직, 제품 검색', [['status','모든 상태',['New','Open','Waiting for customer','Waiting for team','Resolved','Closed']], ['severity','모든 심각도',['S1','S2','S3','S4']], ['incident','Incident 전체',['linked','unlinked']]]); const rows = items.length ? items.map((c) => { const s = sla(c); return `<button class="entity-row ${c.id === selected.id ? 'active' : ''}" data-action="case" data-id="${c.id}"><div class="row"><strong>${c.id.toUpperCase()}</strong>${badge(c.severity, c.severity < 'S3' ? 'red' : 'amber')}</div><p>${esc(c.title)}</p><small>${esc(find(data.organizations,c.organizationId).name)} · ${esc(c.product)}</small><div class="row">${badge(status(c.status))}${badge(s[0],s[1])}</div></button>`; }).join('') : empty('검색 결과가 없습니다'); return entityShell('케이스', items.length, rows, selected ? caseDetail(selected) : '', filters); }
function caseDetail(c) { const conv = find(data.conversations,c.conversationId), u=find(data.customers,c.customerId), o=find(data.organizations,c.organizationId), i=find(data.incidents,c.incidentId), s=sla(c); return `<div class="entity-detail-head"><div><div class="eyebrow">${c.id.toUpperCase()}</div><h2>${esc(c.title)}</h2><div class="meta">${badge(status(c.status))}${badge(c.severity,c.severity < 'S3'?'red':'amber')}${badge(`SLA ${s[0]}`,s[1])}</div></div><div class="detail-actions"><select data-case-field="status"><option value="">상태 변경</option>${options(['New','Open','Waiting for customer','Waiting for team','Resolved','Closed'])}</select><select data-case-field="severity"><option value="">심각도 변경</option>${options(['S1','S2','S3','S4'])}</select><select data-case-field="assigneeId"><option value="">담당자 변경</option>${data.members.map((m)=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></div></div><div class="entity-detail-body"><section class="detail-block"><h3>케이스 개요</h3><dl class="detail-grid"><dt>우선순위</dt><dd>${c.priority}</dd><dt>담당자</dt><dd>${find(data.members,c.assigneeId)?.name || '미배정'}</dd><dt>담당 팀</dt><dd>${find(data.teams,c.teamId)?.name || '미배정'}</dd><dt>해결 내용</dt><dd>${esc(c.resolution || '아직 기록되지 않았습니다.')}</dd></dl></section><section class="detail-block"><h3>기술 정보</h3><dl class="detail-grid">${Object.entries(conv.technical).filter(([k])=>['product','environment','region','version','errorCode','requestId','impact'].includes(k)).map(([k,v])=>`<dt>${({product:'제품',environment:'환경',region:'리전',version:'버전',errorCode:'오류 코드',requestId:'Request ID',impact:'고객 영향'})[k]}</dt><dd>${esc(v || '—')}</dd>`).join('')}</dl></section><section class="detail-block"><h3>연결된 항목</h3><div class="relationship-grid"><button data-action="open-conversation" data-id="${conv.id}">대화<strong>${esc(conv.title)}</strong></button><button data-action="open-customer" data-id="${u.id}">고객<strong>${esc(u.name)}</strong></button><button data-action="open-organization" data-id="${o.id}">조직<strong>${esc(o.name)}</strong></button>${i ? `<button data-action="open-incident" data-id="${i.id}">Incident<strong>${i.id.toUpperCase()} · ${esc(i.title)}</strong></button><button data-action="unlink-incident" data-id="${c.id}">Incident<strong>연결 해제</strong></button>` : `<button data-action="link-incident" data-id="${c.id}">Incident<strong>연결하기</strong></button>`}</div></section><section class="detail-block"><h3>활동</h3><ul class="timeline">${c.activity.map((a)=>`<li>${esc(a.time)} · ${esc(a.text)}</li>`).join('')}</ul></section></div>`; }
function searchFilters(menu, placeholder, selects) { return `<input class="search-input" data-filter-menu="${menu}" data-filter-key="query" value="${esc(filter(menu,'query'))}" placeholder="${placeholder}"><div class="filter-row">${selects.map(([key,label,values])=>`<select data-filter-menu="${menu}" data-filter-key="${key}"><option value="">${label}</option>${values.map(v=>`<option value="${esc(v)}"${filter(menu,key)===v?' selected':''}>${esc(v==='linked'?'연결됨':v==='unlinked'?'미연결':status(v))}</option>`).join('')}</select>`).join('')}</div>`; }
function options(values) { return values.map((v) => `<option value="${esc(v)}">${esc(v === 'linked' ? '연결됨' : v === 'unlinked' ? '미연결' : status(v))}</option>`).join(''); }
function empty(message) { return `<div class="empty-state"><strong>${message}</strong><p>검색어 또는 필터를 변경해 보세요.</p></div>`; }
function customersView() { const q=filter('customers','query').toLowerCase(); const items=data.customers.filter((u)=>`${u.name} ${u.email} ${u.userId} ${find(data.organizations,u.organizationId).name}`.toLowerCase().includes(q)); const selected=items.find((u)=>u.id===state.selectedCustomerId)||items[0]; const rows=items.map((u)=>`<button class="entity-row ${u.id===selected?.id?'active':''}" data-action="customer" data-id="${u.id}"><strong>${esc(u.name)}</strong><p>${esc(u.email)}</p><small>${esc(find(data.organizations,u.organizationId).name)} · ${u.timezone}</small><div>${badge(`${relatedCases('customer',u.id).filter(openCase).length} 열린 Case`)}</div></button>`).join('')||empty('검색 결과가 없습니다'); const detail=selected ? `<div class="entity-detail-head"><div><div class="eyebrow">CUSTOMER</div><h2>${esc(selected.name)}</h2><div class="meta">${esc(selected.role)} · ${selected.language} · ${selected.timezone}</div></div></div><div class="entity-detail-body"><section class="detail-block"><h3>프로필</h3><dl class="detail-grid"><dt>이메일</dt><dd>${esc(selected.email)}</dd><dt>User ID</dt><dd>${esc(selected.userId)}</dd><dt>최근 접속</dt><dd>${esc(selected.lastSeenAt)}</dd><dt>조직</dt><dd><button class="link-button" data-action="open-organization" data-id="${selected.organizationId}">${esc(find(data.organizations,selected.organizationId).name)}</button></dd></dl></section><section class="detail-block"><h3>최근 대화</h3>${list(data.conversations.filter(c=>c.customerId===selected.id).map(c=>`<button class="linked" data-action="open-conversation" data-id="${c.id}"><strong>${esc(c.title)}</strong><span>${status(c.status)}</span></button>`))}</section><section class="detail-block"><h3>Case</h3>${list(relatedCases('customer',selected.id).map(c=>`<button class="linked" data-action="open-case" data-id="${c.id}"><strong>${c.id.toUpperCase()} · ${esc(c.title)}</strong><span>${status(c.status)}</span></button>`))}</section></div>`:''; return entityShell('고객',items.length,rows,detail,searchFilters('customers','이름, 이메일, 조직 검색',[])); }
function organizationsView() { const q=filter('organizations','query').toLowerCase(); const items=data.organizations.filter((o)=>`${o.name} ${o.domain} ${o.productNames.join(' ')}`.toLowerCase().includes(q)); const selected=items.find((o)=>o.id===state.selectedOrganizationId)||items[0]; const rows=items.map((o)=>`<button class="entity-row ${o.id===selected?.id?'active':''}" data-action="organization" data-id="${o.id}"><strong>${esc(o.name)}</strong><p>${esc(o.domain)}</p><small>${o.plan} · ${esc(o.country)}</small><div>${badge(`${relatedCases('organization',o.id).filter(openCase).length} 열린 Case`)}</div></button>`).join('')||empty('검색 결과가 없습니다'); const detail=selected ? `<div class="entity-detail-head"><div><div class="eyebrow">ORGANIZATION</div><h2>${esc(selected.name)}</h2><div class="meta">${selected.plan} · ${selected.contractTier}</div></div></div><div class="entity-detail-body"><section class="detail-block"><h3>계정</h3><dl class="detail-grid"><dt>도메인</dt><dd>${esc(selected.domain)}</dd><dt>CSM</dt><dd>${esc(selected.csmName)}</dd><dt>워크스페이스</dt><dd>${esc(selected.workspaceNames.join(', '))}</dd><dt>제품</dt><dd>${esc(selected.productNames.join(', '))}</dd><dt>상태</dt><dd>${selected.accountStatus}</dd></dl></section><section class="detail-block"><h3>소속 고객</h3>${list(data.customers.filter(u=>u.organizationId===selected.id).map(u=>`<button class="linked" data-action="open-customer" data-id="${u.id}"><strong>${esc(u.name)}</strong><span>${esc(u.role)}</span></button>`))}</section><section class="detail-block"><h3>열린 Case / 영향 Incident</h3>${list(relatedCases('organization',selected.id).map(c=>`<button class="linked" data-action="open-case" data-id="${c.id}"><strong>${c.id.toUpperCase()} · ${esc(c.title)}</strong><span>${status(c.status)}</span></button>`))}</section></div>`:''; return entityShell('조직',items.length,rows,detail,searchFilters('organizations','회사, 도메인, 제품 검색',[])); }
function incidentsView() { const q=filter('incidents','query').toLowerCase(), st=filter('incidents','status'); const items=data.incidents.filter((i)=>`${i.id} ${i.title} ${i.affectedProducts.join(' ')} ${i.affectedRegions.join(' ')}`.toLowerCase().includes(q)&&(!st||i.status===st)); const selected=items.find(i=>i.id===state.selectedIncidentId)||items[0]; const rows=items.map(i=>{const n=incidentCounts(i.id);return `<button class="entity-row ${i.id===selected?.id?'active':''}" data-action="incident" data-id="${i.id}"><div class="row"><strong>${i.id.toUpperCase()}</strong>${badge(status(i.status),i.status==='Resolved'?'blue':'red')}</div><p>${esc(i.title)}</p><small>${esc(i.affectedProducts.join(', '))} · ${esc(i.affectedRegions.join(', '))}</small><div>${badge(`${n.customers} 고객 · ${n.cases.length} Case`)}</div></button>`}).join('')||empty('검색 결과가 없습니다'); const detail=selected ? incidentDetail(selected):''; return entityShell('Incident',items.length,rows,detail,`${searchFilters('incidents','Incident ID, 제목, 제품, 리전 검색',[['status','모든 상태',['Investigating','Identified','Monitoring','Resolved']]])}<button class="secondary full-button" data-action="new-incident">새 Incident</button>`); }
function incidentDetail(i) { const n=incidentCounts(i.id); return `<div class="entity-detail-head"><div><div class="eyebrow">${i.id.toUpperCase()}</div><h2>${esc(i.title)}</h2><div class="meta">${badge(status(i.status),i.status==='Resolved'?'blue':'red')}${badge(i.severity,'red')}</div></div><div class="detail-actions"><select data-incident-field="status"><option value="">상태 변경</option>${options(['Investigating','Identified','Monitoring','Resolved'])}</select></div></div><div class="entity-detail-body"><section class="detail-block"><h3>영향 범위</h3><dl class="detail-grid"><dt>제품</dt><dd>${esc(i.affectedProducts.join(', '))}</dd><dt>리전</dt><dd>${esc(i.affectedRegions.join(', '))}</dd><dt>담당 팀</dt><dd>${find(data.teams,i.ownerTeamId)?.name}</dd><dt>영향</dt><dd>${n.customers} 고객 · ${n.organizations} 조직 · ${n.cases.length} Case</dd></dl></section><section class="detail-block"><h3>공개 업데이트</h3>${i.updates.map(u=>`<div class="update"><strong>${status(u.status)}</strong><p>${esc(u.message)}</p><small>${u.createdAt}</small></div>`).join('')}<textarea data-incident-update placeholder="고객에게 알릴 업데이트"></textarea><button class="send" data-action="add-incident-update" data-id="${i.id}">업데이트 추가</button></section><section class="detail-block"><h3>연결된 Case</h3>${list(n.cases.map(c=>`<button class="linked" data-action="open-case" data-id="${c.id}"><strong>${c.id.toUpperCase()} · ${esc(c.title)}</strong><span>${status(c.status)}</span></button>`))}</section></div>`; }
function knowledgeView() { const q=filter('knowledge','query').toLowerCase(); const items=data.articles.filter(a=>`${a.title} ${a.summary} ${a.category} ${a.relatedProducts.join(' ')}`.toLowerCase().includes(q)); const selected=items.find(a=>a.id===state.selectedArticleId)||items[0]; const rows=items.map(a=>`<button class="entity-row ${a.id===selected?.id?'active':''}" data-action="article" data-id="${a.id}"><strong>${esc(a.title)}</strong><p>${esc(a.summary)}</p><small>${esc(a.category)} · ${esc(a.relatedProducts.join(', '))}</small><div>${badge(a.visibility,a.visibility==='Public'?'blue':'amber')}</div></button>`).join('')||empty('검색 결과가 없습니다'); const insert=selected?.visibility==='Public'?`<button class="secondary" data-action="insert-article" data-id="${selected.id}">답장에 삽입</button>`:`<button class="secondary" disabled>${selected?.visibility} 문서는 고객 답장에 삽입할 수 없습니다</button>`; const visibility=['Public','Internal','Draft'].map(v=>`<option value="${v}"${v===selected.visibility?' selected':''}>${v}</option>`).join(''); const detail=selected ? `<div class="entity-detail-head"><div><div class="eyebrow">ARTICLE</div><h2>${esc(selected.title)}</h2><div class="meta">${badge(selected.visibility)}</div></div><div class="detail-actions">${insert}<button class="secondary" data-action="save-article" data-id="${selected.id}">저장</button></div></div><div class="entity-detail-body"><section class="detail-block"><div class="field"><label>제목</label><input data-article-field="title" value="${esc(selected.title)}"></div><div class="field"><label>요약</label><input data-article-field="summary" value="${esc(selected.summary)}"></div><div class="field"><label>본문</label><textarea data-article-field="body">${esc(selected.body)}</textarea></div><div class="grid-2"><div class="field"><label>카테고리</label><input data-article-field="category" value="${esc(selected.category)}"></div><div class="field"><label>공개 상태</label><select data-article-field="visibility">${visibility}</select></div></div><p class="muted">고객 답장에는 Public 문서만 삽입할 수 있습니다.</p></section></div>`:''; return entityShell('지식',items.length,rows,detail,`${searchFilters('knowledge','제목, 요약, 카테고리, 제품 검색',[])}<button class="secondary full-button" data-action="new-article">새 문서</button>`); }
function analyticsView() { const open=data.cases.filter(openCase), risky=open.filter(c=>sla(c)[1]!=='blue'), active=data.incidents.filter(i=>i.status!=='Resolved'); const by=(arr,key)=>Object.entries(arr.reduce((m,x)=>{const v=typeof key==='function'?key(x):x[key];m[v]=(m[v]||0)+1;return m;},{})); const bars=(entries)=>entries.map(([k,v])=>`<div class="metric-row"><span>${esc(k)}</span><div><i style="width:${Math.max(12,v*35)}%"></i></div><strong>${v}</strong></div>`).join('')||'<p class="muted">데이터가 없습니다.</p>'; return `<main class="analytics-shell">${nav()}<section class="analytics"><div class="entity-detail-head"><div><div class="eyebrow">ANALYTICS</div><h2>지원 운영 현황</h2><p class="muted">건수는 현재 공용 데이터에서 계산됩니다.</p></div></div><div class="kpi-grid"><div class="kpi"><span>총 Conversation</span><strong>${data.conversations.length}</strong></div><div class="kpi"><span>열린 Case</span><strong>${open.length}</strong></div><div class="kpi"><span>미배정 Conversation</span><strong>${data.conversations.filter(c=>!c.assigneeId).length}</strong></div><div class="kpi"><span>진행 중 Incident</span><strong>${active.length}</strong></div><div class="kpi"><span>SLA 위험</span><strong>${risky.length}</strong></div><div class="kpi"><span>평균 최초 응답</span><strong>${data.analyticsBenchmarks.firstResponse}</strong></div></div><div class="analytics-grid"><section class="detail-block"><h3>Issue Insights</h3><h4>제품별 Case</h4>${bars(by(data.cases,'product'))}<h4>리전별 기술 문의</h4>${bars(by(data.conversations,c=>c.technical.region))}</section><section class="detail-block"><h3>Team Performance</h3><h4>담당자별 열린 Case</h4>${bars(by(open,c=>find(data.members,c.assigneeId)?.name||'미배정'))}<h4>SLA 상태</h4>${bars(by(data.cases,c=>sla(c)[0].includes('초과')?'초과':sla(c)[0].includes('남음')?'진행':'완료'))}</section></div></section></main>`; }
function modal() { if (!state.modal) return ''; if (state.modal.type==='link-incident') return `<div class="modal-backdrop"><div class="modal"><h2>Incident 연결</h2><p class="muted">연결할 Incident를 선택하세요.</p>${data.incidents.filter(i=>i.status!=='Resolved').map(i=>`<button class="linked" data-action="confirm-link-incident" data-id="${i.id}" data-case-id="${state.modal.caseId}"><strong>${i.id.toUpperCase()} · ${esc(i.title)}</strong><span>${status(i.status)}</span></button>`).join('')}<div class="actions"><button class="secondary" data-action="close-modal">취소</button></div></div></div>`; if(state.modal.type==='new-incident')return `<div class="modal-backdrop"><div class="modal"><h2>새 Incident</h2><div class="field"><label>제목</label><input data-new-incident="title" value="New service incident"></div><div class="field"><label>심각도</label><select data-new-incident="severity">${options(['S1','S2','S3','S4'])}</select></div><div class="field"><label>영향 제품</label><input data-new-incident="product" value="Public API"></div><div class="field"><label>영향 리전</label><input data-new-incident="region" value="EU-West"></div><div class="actions"><button class="secondary" data-action="close-modal">취소</button><button class="send" data-action="create-incident">생성</button></div></div></div>`; return ''; }
function render() { const views={inbox:inboxView,cases:casesView,customers:customersView,organizations:organizationsView,incidents:incidentsView,knowledge:knowledgeView,analytics:analyticsView}; app.innerHTML=shell(state.mode==='customer'?customerView():views[state.activeAgentMenu]())+modal(); }
function notify(message) { setState({toast:message}); render(); window.setTimeout(()=>{if(state.toast===message){setState({toast:''});render();}},2200); }
function navigate(type,id) { setState({mode:'agent',activeAgentMenu:type==='conversation'?'inbox':`${type}s`, [`selected${type[0].toUpperCase()+type.slice(1)}Id`]:id}); render(); }
function createCase(conversationId) { const c=find(data.conversations,conversationId); if(c.caseId)return navigate('case',c.caseId); const id=`case-${Date.now()}`; data.cases.unshift({id,conversationId:c.id,customerId:c.customerId,organizationId:c.organizationId,incidentId:c.incidentId,title:c.title,type:c.type,product:c.technical.product,environment:c.technical.environment,priority:c.priority,severity:'S3',status:'New',assigneeId:c.assigneeId,teamId:c.teamId,slaDueAt:'2026-07-23T14:00:00Z',resolution:'',createdAt:NOW.toISOString(),updatedAt:NOW.toISOString(),activity:[{time:'방금',text:'Alex Kim이 Inbox 대화에서 Case를 생성했습니다.'}]}); c.caseId=id; navigate('case',id); notify('지원 케이스를 생성했습니다.'); }
function submitRequest() { const f=state.customerForm; if(!f.product||!f.region||!f.message.trim()) return notify('제품, 리전, 문의 내용은 필수입니다.'); const id=`conv-${Date.now()}`; data.conversations.unshift({id,customerId:'u-maya',organizationId:'o-acme',caseId:null,incidentId:null,title:`${f.product} issue in ${f.region}`,type:'Technical issue',status:'New',priority:'High',assigneeId:null,teamId:'t-support',tagIds:[],createdAt:NOW.toISOString(),updatedAt:NOW.toISOString(),technical:{...f},messages:[{from:'Maya Chen',type:'customer',time:'방금',text:f.message}]}); setState({selectedConversationId:id,customerStep:'chat'}); notify('기술 지원팀에 문의를 보냈습니다.'); }
function updateCase(id, field, value) { const c=find(data.cases,id), before=c[field]; c[field]=value;c.updatedAt=NOW.toISOString(); c.activity.unshift({time:'방금',text:`Alex Kim이 ${field==='status'?'상태':field==='severity'?'심각도':'담당자'}를 ${before||'미배정'} → ${value}로 변경했습니다.`}); notify('케이스 정보를 변경했습니다.'); }
document.addEventListener('click',(event)=>{ const el=event.target.closest('[data-action]'); if(!el)return; const a=el.dataset.action,id=el.dataset.id;
  if(a==='menu')setState({activeAgentMenu:id});
  if(a==='mode')setState({mode:id}); if(a==='customer-step')setState({customerStep:id});
  if(a==='inbox-queue'){const q=id==='mine'?data.conversations.filter(c=>c.assigneeId==='m-alex'):data.conversations;setState({inboxQueue:id,selectedConversationId:q[0]?.id||null});}
  if(a==='conversation')setState({selectedConversationId:id}); if(a==='case')setState({selectedCaseId:id}); if(a==='customer')setState({selectedCustomerId:id}); if(a==='organization')setState({selectedOrganizationId:id}); if(a==='incident')setState({selectedIncidentId:id}); if(a==='article')setState({selectedArticleId:id});
  if(a==='open-conversation')navigate('conversation',id); if(a==='open-case')navigate('case',id); if(a==='open-customer')navigate('customer',id); if(a==='open-organization')navigate('organization',id); if(a==='open-incident')navigate('incident',id);
  if(a==='create-case')createCase(id); if(a==='submit-request')submitRequest(); if(a==='composer-mode')setState({composerMode:id});
  if(a==='use-macro')setState({composerText:state.composerText ? `${state.composerText}\n\n제보 감사합니다. 현재 담당 팀에서 문제를 조사하고 있으며, 새로운 정보가 확인되는 대로 안내하겠습니다.` : '제보 감사합니다. 현재 담당 팀에서 문제를 조사하고 있으며, 새로운 정보가 확인되는 대로 안내하겠습니다.'});
  if(a==='send-message'){const c=find(data.conversations,state.selectedConversationId),text=state.composerText.trim(); if(!text) return notify('메시지를 먼저 작성하세요.'); const internal=state.composerMode==='internal';c.messages.push({from:'Alex Kim',type:internal?'internal':'agent',time:'방금',text});if(!internal)c.status='Waiting for customer';setState({composerText:''});notify(internal?'내부 메모를 추가했습니다.':'답장을 보냈습니다.');}
  if(a==='open-knowledge')setState({activeAgentMenu:'knowledge'});
  if(a==='link-incident')setState({modal:{type:'link-incident',caseId:id}}); if(a==='confirm-link-incident'){const c=find(data.cases,el.dataset.caseId),conv=find(data.conversations,c.conversationId);c.incidentId=id;conv.incidentId=id;c.activity.unshift({time:'방금',text:`Alex Kim이 ${id.toUpperCase()} Incident를 연결했습니다.`});setState({modal:null});notify('Incident를 연결했습니다.');}
  if(a==='unlink-incident'){const c=find(data.cases,id);find(data.conversations,c.conversationId).incidentId=null;c.incidentId=null;c.activity.unshift({time:'방금',text:'Alex Kim이 Incident 연결을 해제했습니다.'});notify('Incident 연결을 해제했습니다.');}
  if(a==='add-incident-update'){const input=app.querySelector('[data-incident-update]'),i=find(data.incidents,id),text=input.value.trim();if(!text)return notify('업데이트 내용을 입력하세요.');i.updates.unshift({id:`upd-${Date.now()}`,status:i.status,message:text,createdAt:NOW.toISOString(),authorId:'m-alex'});notify('공개 업데이트를 추가했습니다.');}
  if(a==='new-incident')setState({modal:{type:'new-incident'}}); if(a==='close-modal')setState({modal:null});
  if(a==='create-incident'){const get=(k)=>app.querySelector(`[data-new-incident="${k}"]`).value;const id=`inc-${Date.now()}`;data.incidents.unshift({id,title:get('title'),severity:get('severity'),status:'Investigating',affectedProducts:[get('product')],affectedRegions:[get('region')],ownerTeamId:'t-platform',startedAt:NOW.toISOString(),resolvedAt:null,updates:[]});setState({modal:null,selectedIncidentId:id,activeAgentMenu:'incidents'});notify('새 Incident를 생성했습니다.');}
  if(a==='new-article'){const id=`art-${Date.now()}`;data.articles.unshift({id,title:'새 문서',summary:'',body:'',category:'Getting started',language:'English',relatedProducts:[],visibility:'Draft',url:'https://help.relaydesk.example/draft',updatedAt:'방금',authorId:'m-alex'});setState({selectedArticleId:id});notify('새 문서를 만들었습니다.');}
  if(a==='insert-article'){const article=find(data.articles,id);setState({activeAgentMenu:'inbox',composerMode:'reply',composerText:`${state.composerText}${state.composerText?'\n\n':''}${article.title}: ${article.url}`});notify('공개 문서 링크를 답장에 삽입했습니다.');}
  if(a==='save-article'){const article=find(data.articles,id);app.querySelectorAll('[data-article-field]').forEach(input=>article[input.dataset.articleField]=input.value);article.updatedAt='방금';notify('문서를 저장했습니다.');}
  render();
});
document.addEventListener('input',(event)=>{const el=event.target;if(el.dataset.composerInput!==undefined)setState({composerText:el.value}); if(el.dataset.customerField)setState({customerForm:{...state.customerForm,[el.dataset.customerField]:el.value}}); if(el.dataset.filterMenu){setFilter(el.dataset.filterMenu,el.dataset.filterKey,el.value);render();}});
document.addEventListener('change',(event)=>{const el=event.target;if(el.dataset.filterMenu){setFilter(el.dataset.filterMenu,el.dataset.filterKey,el.value);render();} if(el.dataset.caseField&&el.value)updateCase(state.selectedCaseId,el.dataset.caseField,el.value); if(el.dataset.incidentField&&el.value){const i=find(data.incidents,state.selectedIncidentId);i.status=el.value;if(el.value==='Resolved')i.resolvedAt=NOW.toISOString();notify('Incident 상태를 변경했습니다.');}});
render();
