import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createCase, loadMessages, loadWorkspace, sendMessage, updateCase } from './repository';
import { isConfigured, supabase } from './supabase';
import type { Conversation, Message, SupportCase, WorkspaceData } from './types';
import { workspaceMetrics } from './metrics';

type View = 'inbox' | 'cases' | 'incidents' | 'analytics';
const empty: WorkspaceData = { conversations: [], cases: [], incidents: [] };
const date = (value: string) => new Intl.DateTimeFormat('ko-KR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value));

export function App() {
  const [sessionReady, setSessionReady] = useState(!isConfigured);
  const [data, setData] = useState<WorkspaceData>(empty);
  const [view, setView] = useState<View>('inbox');
  const [selected, setSelected] = useState<string>();
  const [messages, setMessages] = useState<Message[]>([]);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');

  const refresh = async () => { setLoading(true); setError(''); try { const next = await loadWorkspace(); setData(next); setSelected(id => id || next.conversations[0]?.id); } catch (e) { setError(e instanceof Error ? e.message : '데이터를 불러오지 못했습니다.'); } finally { setLoading(false); } };
  useEffect(() => { if (!isConfigured) return; supabase!.auth.getSession().then(({ data }) => setSessionReady(Boolean(data.session))); const { data: listener } = supabase!.auth.onAuthStateChange((_event, session) => setSessionReady(Boolean(session))); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { if (sessionReady) void refresh(); }, [sessionReady]);
  const conversation = data.conversations.find(item => item.id === selected) || data.conversations[0];
  useEffect(() => { if (conversation) loadMessages(conversation.id).then(setMessages).catch(e => setError(e.message)); }, [conversation?.id]);
  if (!sessionReady) return <Login onDone={() => setSessionReady(true)} />;
  const filtered = data.conversations.filter(item => `${item.title} ${item.customer_name} ${item.organization_name}`.toLowerCase().includes(query.toLowerCase()));
  const caseForConversation = conversation && data.cases.find(item => item.conversation_id === conversation.id);
  return <div className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">R</span>RelayDesk <small>pilot</small></div><div className="top-actions"><span className="muted">{isConfigured ? '파일럿 워크스페이스' : '로컬 데모 모드'}</span><button className="secondary" onClick={() => void refresh()}>새로고침</button>{isConfigured && <button className="secondary" onClick={() => void supabase!.auth.signOut()}>로그아웃</button>}</div></header>
    {error && <div className="notice error">{error}</div>}
    {!isConfigured && <div className="notice">Supabase 환경 변수가 없습니다. 현재 데이터는 이 브라우저에만 저장됩니다.</div>}
    <main className="agent-shell">
      <nav className="nav">{([['inbox','인박스'],['cases','케이스'],['incidents','Incident'],['analytics','분석']] as [View,string][]).map(([id,label]) => <button key={id} className={`nav-item ${view === id ? 'active' : ''}`} onClick={() => setView(id)}>{label}</button>)}</nav>
      {view === 'inbox' && <><aside className="sidebar"><div className="sidebar-head"><div className="row"><h2>Inbox</h2><span className="muted">{filtered.length}건</span></div><input aria-label="대화 검색" className="search-input" value={query} onChange={e => setQuery(e.target.value)} placeholder="고객, 조직, 제목 검색" /></div>{filtered.map(item => <button className={`conversation ${conversation?.id === item.id ? 'active' : ''}`} key={item.id} onClick={() => setSelected(item.id)}><div className="row"><strong>{item.customer_name}</strong><Badge value={item.priority}/></div><small>{item.organization_name}</small><p>{item.title}</p><span className="muted">{item.status}</span></button>)}</aside><ConversationDetail conversation={conversation} messages={messages} supportCase={caseForConversation} onCreate={async () => { if (conversation) { await createCase(conversation); await refresh(); } }} onSend={async (body, kind) => { if (conversation) { await sendMessage(conversation.id, body, kind); setMessages(await loadMessages(conversation.id)); await refresh(); } }} /><aside className="context">{conversation && <><h3>기술 컨텍스트</h3><dl className="key-value"><dt>고객</dt><dd>{conversation.customer_name}</dd><dt>조직</dt><dd>{conversation.organization_name}</dd>{Object.entries(conversation.technical).map(([k,v]) => <><dt key={`${k}-k`}>{label(k)}</dt><dd key={k}>{v || '—'}</dd></>)}</dl></>}</aside></>}
      {view === 'cases' && <Cases cases={data.cases} incidents={data.incidents} onChange={async (id, patch) => { await updateCase(id, patch); await refresh(); }} />}
      {view === 'incidents' && <section className="wide-panel"><h1>Incident</h1>{data.incidents.map(item => <article className="card" key={item.id}><div className="row"><h2>{item.title}</h2><Badge value={item.severity}/></div><p>{item.status} · 마지막 변경 {date(item.updated_at)}</p></article>)}</section>}
      {view === 'analytics' && <Analytics data={data}/>} 
    </main>
    {loading && <div className="loading">동기화 중…</div>}
  </div>;
}

function Login({ onDone }: { onDone: () => void }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); const { error } = await supabase!.auth.signInWithPassword({ email, password }); if (error) setError(error.message); else onDone(); }; return <main className="login"><section className="card"><div className="brand"><span className="brand-mark">R</span>RelayDesk</div><h1>지원 워크스페이스 로그인</h1><p className="muted">사전 발급된 파일럿 계정으로 로그인하세요.</p><form onSubmit={submit}><label>이메일<input required type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>비밀번호<input required type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button className="primary">로그인</button></form></section></main>; }
function ConversationDetail({ conversation, messages, supportCase, onCreate, onSend }: { conversation?: Conversation; messages: Message[]; supportCase?: SupportCase; onCreate: () => Promise<void>; onSend: (body: string, kind: 'agent'|'internal') => Promise<void> }) { const [body, setBody] = useState(''); const [kind, setKind] = useState<'agent'|'internal'>('agent'); if (!conversation) return <section className="detail"><div className="empty-state">대화를 선택하세요.</div></section>; const submit = async (event: FormEvent) => { event.preventDefault(); if (!body.trim()) return; await onSend(body.trim(), kind); setBody(''); }; return <section className="detail"><div className="detail-head"><div><h2>{conversation.title}</h2><div className="meta">{supportCase ? <strong>{supportCase.id.slice(0,8)} · {supportCase.status}</strong> : <button className="link-button" onClick={() => void onCreate()}>지원 Case 생성</button>}</div></div><Badge value={conversation.status}/></div><div className="thread">{messages.map(message => <div key={message.id} className={`thread-message ${message.kind === 'internal' ? 'internal' : ''}`}><div className="avatar">{message.author_name.slice(0,2)}</div><div className="content"><strong>{message.author_name}</strong>{message.kind === 'internal' && <span className="internal-label"> · 내부 메모</span>}<p>{message.body}</p><span className="muted">{date(message.created_at)}</span></div></div>)}</div><form className="composer-agent" onSubmit={submit}><div className="composer-type"><button type="button" className={kind === 'agent' ? 'active' : ''} onClick={() => setKind('agent')}>답장</button><button type="button" className={kind === 'internal' ? 'active' : ''} onClick={() => setKind('internal')}>내부 메모</button></div><textarea value={body} onChange={e => setBody(e.target.value)} placeholder={kind === 'internal' ? '내부 메모를 작성하세요…' : '고객에게 답장하기…'} /><button className="send">{kind === 'internal' ? '메모 추가' : '답장 보내기'}</button></form></section>; }
function Cases({ cases, incidents, onChange }: { cases: SupportCase[]; incidents: WorkspaceData['incidents']; onChange: (id: string, patch: Partial<Pick<SupportCase,'status'|'severity'|'incident_id'>>) => Promise<void> }) { const [selected, setSelected] = useState(cases[0]?.id); const item = cases.find(c => c.id === selected) || cases[0]; return <><aside className="sidebar"><div className="sidebar-head"><h2>케이스</h2></div>{cases.map(c => <button className={`conversation ${item?.id === c.id ? 'active' : ''}`} key={c.id} onClick={() => setSelected(c.id)}><strong>{c.title}</strong><p><Badge value={c.severity}/> {c.status}</p></button>)}</aside><section className="detail">{item && <><div className="detail-head"><h1>{item.title}</h1><Badge value={item.severity}/></div><div className="field-grid"><label>상태<select value={item.status} onChange={e => void onChange(item.id, { status: e.target.value as SupportCase['status'] })}>{['New','Open','Waiting for customer','Waiting for team','Resolved','Closed'].map(v => <option key={v}>{v}</option>)}</select></label><label>심각도<select value={item.severity} onChange={e => void onChange(item.id, { severity: e.target.value as SupportCase['severity'] })}>{['S1','S2','S3','S4'].map(v => <option key={v}>{v}</option>)}</select></label><label>Incident<select value={item.incident_id || ''} onChange={e => void onChange(item.id, { incident_id: e.target.value || null })}><option value="">연결 안 함</option>{incidents.map(i => <option value={i.id} key={i.id}>{i.title}</option>)}</select></label></div><p className="muted">변경은 활동 이력과 함께 저장됩니다.</p></>}</section><aside className="context"><h3>운영 원칙</h3><p>Case는 조사와 추적이 필요한 문의에만 생성합니다.</p></aside></>; }
function Analytics({ data }: { data: WorkspaceData }) { const metrics = workspaceMetrics(data); return <section className="wide-panel"><h1>분석</h1><div className="metric-grid"><Metric label="열린 Case" value={metrics.openCases}/><Metric label="진행 Incident" value={metrics.activeIncidents}/><Metric label="Incident 연결" value={metrics.incidentLinkedCases}/><Metric label="S1/S2 Case" value={metrics.criticalCases}/></div><p className="muted">모든 수치는 현재 워크스페이스 데이터에서 계산됩니다.</p></section>; }
function Metric({ label, value }: { label: string; value: number }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article>; }
function Badge({ value }: { value: string }) { return <span className={`badge ${value === 'High' || value === 'S1' || value === 'S2' ? 'red' : 'blue'}`}>{value}</span>; }
function label(value: string) { return ({ product: '제품', environment: '환경', region: '리전', errorCode: '오류 코드', requestId: 'Request ID' } as Record<string,string>)[value] || value; }
