-- RelayDesk pilot: one authenticated user belongs to one or more isolated workspaces.
create extension if not exists pgcrypto;

create type public.member_role as enum ('admin', 'agent');
create type public.case_status as enum ('New', 'Open', 'Waiting for customer', 'Waiting for team', 'Resolved', 'Closed');
create type public.message_kind as enum ('customer', 'agent', 'internal');
create type public.incident_status as enum ('Investigating', 'Identified', 'Monitoring', 'Resolved');

create table public.workspaces (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users on delete cascade, display_name text not null, created_at timestamptz not null default now());
create table public.memberships (workspace_id uuid not null references public.workspaces on delete cascade, profile_id uuid not null references public.profiles on delete cascade, role public.member_role not null default 'agent', primary key (workspace_id, profile_id));
create table public.organizations (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, name text not null, plan text, created_at timestamptz not null default now());
create table public.customers (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, organization_id uuid not null references public.organizations on delete restrict, name text not null, email text, created_at timestamptz not null default now());
create table public.conversations (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, customer_id uuid not null references public.customers on delete restrict, title text not null, status public.case_status not null default 'New', priority text not null default 'Medium' check (priority in ('High','Medium','Low')), technical jsonb not null default '{}'::jsonb, assignee_id uuid references public.profiles on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.incidents (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, title text not null, status public.incident_status not null default 'Investigating', severity text not null check (severity in ('S1','S2','S3','S4')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.cases (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, conversation_id uuid not null unique references public.conversations on delete restrict, title text not null, status public.case_status not null default 'New', severity text not null default 'S3' check (severity in ('S1','S2','S3','S4')), priority text not null check (priority in ('High','Medium','Low')), incident_id uuid references public.incidents on delete set null, assignee_id uuid references public.profiles on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, conversation_id uuid not null references public.conversations on delete cascade, author_id uuid references public.profiles on delete set null, author_name text not null default 'Customer', kind public.message_kind not null, body text not null check (char_length(body) between 1 and 10000), created_at timestamptz not null default now());
create table public.incident_updates (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, incident_id uuid not null references public.incidents on delete cascade, body text not null check (char_length(body) between 1 and 10000), author_id uuid not null references public.profiles on delete restrict, created_at timestamptz not null default now());
create table public.engineering_issues (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, case_id uuid not null unique references public.cases on delete restrict, title text not null, status text not null default 'Triage', technical_snapshot jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.articles (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, title text not null, body text not null default '', visibility text not null default 'Internal' check (visibility in ('Internal','Public','Draft')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.activity_logs (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, entity_type text not null, entity_id uuid not null, action text not null, actor_id uuid references public.profiles on delete set null, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create or replace function public.current_workspace_ids() returns setof uuid language sql stable security definer set search_path = public as $$ select workspace_id from public.memberships where profile_id = auth.uid() $$;
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
create trigger conversations_touch before update on public.conversations for each row execute function public.touch_updated_at();
create trigger cases_touch before update on public.cases for each row execute function public.touch_updated_at();
create trigger incidents_touch before update on public.incidents for each row execute function public.touch_updated_at();
create trigger issues_touch before update on public.engineering_issues for each row execute function public.touch_updated_at();
create trigger articles_touch before update on public.articles for each row execute function public.touch_updated_at();
create or replace function public.log_case_change() returns trigger language plpgsql as $$ begin if old.status is distinct from new.status or old.severity is distinct from new.severity or old.incident_id is distinct from new.incident_id then insert into public.activity_logs(workspace_id, entity_type, entity_id, action, actor_id, details) values (new.workspace_id, 'case', new.id, 'updated', auth.uid(), jsonb_build_object('status', new.status, 'severity', new.severity, 'incident_id', new.incident_id)); end if; return new; end $$;
create trigger cases_audit after update on public.cases for each row execute function public.log_case_change();

alter table public.workspaces enable row level security; alter table public.profiles enable row level security; alter table public.memberships enable row level security;
alter table public.organizations enable row level security; alter table public.customers enable row level security; alter table public.conversations enable row level security; alter table public.cases enable row level security; alter table public.incidents enable row level security; alter table public.messages enable row level security; alter table public.incident_updates enable row level security; alter table public.engineering_issues enable row level security; alter table public.articles enable row level security; alter table public.activity_logs enable row level security;
create policy "workspace members" on public.workspaces for select using (id in (select public.current_workspace_ids()));
create policy "workspace-scoped profiles read" on public.profiles for select to authenticated using (id = auth.uid() or exists (select 1 from public.memberships mine join public.memberships theirs on theirs.workspace_id = mine.workspace_id where mine.profile_id = auth.uid() and theirs.profile_id = profiles.id));
create policy "members see memberships" on public.memberships for select using (workspace_id in (select public.current_workspace_ids()));
create policy "workspace isolation organizations" on public.organizations for all using (workspace_id in (select public.current_workspace_ids())) with check (workspace_id in (select public.current_workspace_ids()));
create policy "workspace isolation customers" on public.customers for all using (workspace_id in (select public.current_workspace_ids())) with check (workspace_id in (select public.current_workspace_ids()));
create policy "workspace isolation conversations" on public.conversations for all using (workspace_id in (select public.current_workspace_ids())) with check (workspace_id in (select public.current_workspace_ids()));
create policy "workspace isolation cases" on public.cases for all using (workspace_id in (select public.current_workspace_ids())) with check (workspace_id in (select public.current_workspace_ids()));
create policy "workspace isolation incidents" on public.incidents for all using (workspace_id in (select public.current_workspace_ids())) with check (workspace_id in (select public.current_workspace_ids()));
create policy "workspace isolation issues" on public.engineering_issues for all using (workspace_id in (select public.current_workspace_ids())) with check (workspace_id in (select public.current_workspace_ids()));
create policy "workspace isolation articles" on public.articles for all using (workspace_id in (select public.current_workspace_ids())) with check (workspace_id in (select public.current_workspace_ids()));
create policy "workspace members see activity" on public.activity_logs for select using (workspace_id in (select public.current_workspace_ids()));
create policy "agents add activity" on public.activity_logs for insert with check (workspace_id in (select public.current_workspace_ids()));
create policy "members read messages except internal policy is app role" on public.messages for select using (workspace_id in (select public.current_workspace_ids()));
create policy "agents insert messages" on public.messages for insert with check (workspace_id in (select public.current_workspace_ids()) and author_id = auth.uid() and kind in ('agent','internal'));
create policy "members read updates" on public.incident_updates for select using (workspace_id in (select public.current_workspace_ids()));
create policy "agents add updates" on public.incident_updates for insert with check (workspace_id in (select public.current_workspace_ids()) and author_id = auth.uid());

create or replace view public.conversation_list with (security_invoker = true) as
select c.id, c.title, c.status, c.priority, cu.name as customer_name, o.name as organization_name, c.technical, p.display_name as assignee_name, c.updated_at
from public.conversations c join public.customers cu on cu.id = c.customer_id join public.organizations o on o.id = cu.organization_id left join public.profiles p on p.id = c.assignee_id;
create or replace view public.case_list with (security_invoker = true) as
select c.id, c.conversation_id, c.title, c.status, c.severity, c.priority, c.incident_id, p.display_name as assignee_name, c.updated_at from public.cases c left join public.profiles p on p.id = c.assignee_id;

create or replace function public.add_message(p_conversation_id uuid, p_body text, p_kind public.message_kind) returns void language plpgsql security definer set search_path = public as $$
declare v_workspace uuid; begin select workspace_id into v_workspace from public.conversations where id = p_conversation_id and workspace_id in (select public.current_workspace_ids()); if v_workspace is null then raise exception 'Conversation not found'; end if; if p_kind = 'customer' then raise exception 'Customer messages are not accepted through the agent app'; end if; insert into public.messages(workspace_id, conversation_id, author_id, author_name, kind, body) select v_workspace, p_conversation_id, auth.uid(), display_name, p_kind, p_body from public.profiles where id = auth.uid(); update public.conversations set status = case when p_kind = 'agent' then 'Waiting for customer' else status end where id = p_conversation_id; insert into public.activity_logs(workspace_id, entity_type, entity_id, action, actor_id) values (v_workspace, 'conversation', p_conversation_id, p_kind::text || '_message_added', auth.uid()); end $$;
create or replace function public.create_case_from_conversation(p_conversation_id uuid) returns uuid language plpgsql security definer set search_path = public as $$
declare v public.conversations; v_id uuid; begin select * into v from public.conversations where id = p_conversation_id and workspace_id in (select public.current_workspace_ids()); if not found then raise exception 'Conversation not found'; end if; select id into v_id from public.cases where conversation_id = v.id; if v_id is not null then return v_id; end if; insert into public.cases(workspace_id, conversation_id, title, priority, assignee_id) values (v.workspace_id, v.id, v.title, v.priority, v.assignee_id) returning id into v_id; insert into public.activity_logs(workspace_id, entity_type, entity_id, action, actor_id) values (v.workspace_id, 'case', v_id, 'created_from_conversation', auth.uid()); return v_id; end $$;
grant select on public.conversation_list, public.case_list to authenticated;
grant execute on function public.add_message(uuid, text, public.message_kind), public.create_case_from_conversation(uuid) to authenticated;
